### ISSUE TITLE
Umbrella: Short term updates to organise metadata

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#1035]
Tasks to complete:
- [x] Adding in config framework for metadata - #978 
- [x] Adding data_level and data_sublevel keywords - #551
- [x] Ensuring dataset_source/data_source keys can be added and used to distinguish - #654 
- [x] Ensure icoscp is set up correctly (pinned and tests passing) - PR #1084 
- [x] Remove `icos_data_level` and just used `data_level` within required keys - #1067 (PR #1087)
- [x] Remove keys which aren't needed from surface required keys - PR #1088
- [x] Added ability to perform negative lookup - PR #1064
    - Next step would be to integrate this into `standardise` framework

Moved to next milestone:
- ~Allow metadata keys to be added outside the parse framework at the store level class - #1071~ - moved to umbrella #1092
- ~Move functionality which require all metadata out of parse functions and into store level classes - #986~ - moved to umbrella #1092
- ~TUTORIAL's : https://github.com/openghg/openghg/issues/982~ - moved to 0.10.0 release

**Comment by brendan-m-murphy** [comment]
# Table of Contents

1.  [Background on metadata](#org0179e33)
    1.  [What do we use metadata for?](#orgbac4070)
    2.  [Where does metadata come from?](#org97ccb20)
2.  [Improving how we use metadata](#orgeba5722)
    1.  [What is our goal?](#org9f23b45)
    2.  [Requirements](#org06747f9)
    3.  [It would be nice if&#x2026;](#orge169316)
    4.  [Problems](#org8e49bb1)
3.  [Improving how metadata is handled in the code](#orgc227a67)
4.  [Refactorings](#orga0f8f4d)
    1.  [`BaseStore` children `read_file` after parser applied](#orgfc955ae)
    2.  [`read_file` kwargs, most named arguments go through `standardise`?](#org8dc57f3)
    3.  [standardise functions](#org8ec12be)
5.  [Sort out Gareth&rsquo;s PR 983](#org2cd7a21)
    1.  [add code for reading categorising keys from config](#org6baf40c)
    2.  [remaining metadata tasks](#orgc3f0c3d)
    3.  [fix how optional/informative metadata is processed](#orgac1a7d7)
    4.  [summarise existing state](#orga03e37d)
6.  [make methods (and CLI?) for modifying config file](#orgf50c35c)
7.  [extract repeated code for metadata handling from subclasses of `BaseStore`](#org3c5cc25)
8.  [add option for passing additional categorising keys via kwargs](#org6a7e2e3)
9.  [parser organisation](#org99b94e0)
10. [Centralise metadata processing](#org581a31e)
11. [Random related ideas](#org306ebaa)



<a id="org0179e33"></a>

# Background on metadata


<a id="orgbac4070"></a>

## What do we use metadata for?

1.  categorising data (i.e. &ldquo;defining datasources&rdquo;)
2.  searching for data
3.  information about data
4.  data attributes (like 3, but handled differently, must adhere to standards)


<a id="org97ccb20"></a>

## Where does metadata come from?

-   user input (via &ldquo;standardise&rdquo;)
-   extracted from data by parser
-   external data (`openghg_defs`)
-   data attributes (part of parsing?)
-   existing metadata from datasources (currently, we always )


<a id="orgeba5722"></a>

# Improving how we use metadata


<a id="org9f23b45"></a>

## What is our goal?

-   Finer control over how data is grouped
-   Tagging data for easy searching
-   Adding comments to data


<a id="org06747f9"></a>

## Requirements

-   if users want data to be distinguished in a certain way, it should be possible
-   it should be possible to retrieve each datasource uniquely
-   it should be difficult to accidentally group data together (it is possible to combine data later, but usually impossible to split it apart)


<a id="orge169316"></a>

## It would be nice if&#x2026;

-   Adding new keys to distinguish data should be easy (e.g. changes can be made from the user API, possibly automatically through `standardise`)
-   Arbitrary &ldquo;informational&rdquo; metadata (e.g. &ldquo;tags&rdquo;, &ldquo;comments&rdquo;) can be added, but won&rsquo;t change the categorisation of data
-   We should avoid accidentally grouping data together that should not be grouped together (i.e. veer towards being too fine-grained, rather than too coarse-grained)
-   Users should not have to specify every &ldquo;categorising&rdquo; type of metadata
-   We pre-empted problems due to misspellings
-   It is clear to the user what different items of metadata will be used for (categorising or just for search/info?)


<a id="org8e49bb1"></a>

## Problems

-   How do we ensure we have &ldquo;enough&rdquo; metadata to store and retrieve something?
    -   Currently: using &ldquo;required&rdquo; keys; &ldquo;optional&rdquo; keys will be used if present; sometimes only a certain number of &ldquo;required&rdquo; keys must be present
    -   Minimum requirement: that the data can be retrieved uniquely?
        -   what if we only give &ldquo;site&rdquo; for surface obs? If other obs for that site are added, including an inlet and species. This is just the &ldquo;subset&rdquo; problem&#x2026; but it seems undesirable.
        -   On the other hand, this is a very &ldquo;natural&rdquo; set up.
-   What if two datasources (A and B) have all of the same &ldquo;categorising metadata&rdquo;, but B has an additional piece of metadata? How do we retrieve A and B? (&ldquo;subset&rdquo; problem)
    -   need &ldquo;negative&rdquo; lookup: i.e. can specify that we want results where a key is **not** present.
    -   &ldquo;negative&rdquo; lookup might need to be by default in some settings (standardising? retrieval?), and only by specification in other settings (e.g. search)
-   What if data is accidentally stored in a separate/new datasource?
-   What if a new type of &ldquo;categorising&rdquo; metadata is added after data is already in the store? (same as &ldquo;subset&rdquo; problem?)
-   How should new &ldquo;categorising&rdquo; metadata be specified?
    -   we&rsquo;ve decided on using a config file
-   How can users pass &ldquo;categorising&rdquo; metadata separately from &ldquo;informational&rdquo; metadata?


<a id="orgc227a67"></a>

# Improving how metadata is handled in the code


<a id="orga0f8f4d"></a>

# Refactorings


<a id="orgfc955ae"></a>

## `BaseStore` children `read_file` after parser applied


<a id="org8dc57f3"></a>

## `read_file` kwargs, most named arguments go through `standardise`?


<a id="org8ec12be"></a>

## standardise functions

-   use `locals` to pass arguments on to generic `standardise`?


<a id="org2cd7a21"></a>

# TODO Sort out Gareth&rsquo;s PR 983

Issues:

-   prior to this PR, `optional_metadata` was added to the metadata returned from the parser, so it *could* be used for data source lookup if optional metadata was specified via &#x2026; `optional_metadata`. (But it could not be used to specify &ldquo;required&rdquo; metadata)
-   we now want &ldquo;info&rdquo; that is not used to do datasource lookup
    -   solution: add info at standardise level?
-   we (might) want users to be able to add &ldquo;categorising&rdquo; metadata on the fly
    -   this means that context is necessary to determine what is &ldquo;categorising&rdquo; (i.e. config is not enough)
    -   or&#x2026; it means we need to add these new categorising keys to the config
-   All subclasses of `BaseStore` and all &ldquo;standardise&rdquo; functions need to be updated to make these changes.
-   Different subclasses of `BaseStore` process metadata differently:
    -   `flux` has optional keys; the other classes don&rsquo;t
    -   some classes (just `flux`?) have &ldquo;transform&rdquo; pathway
    -   there is also the &ldquo;retrieve&rdquo; pathway

NOTE: I rolled this PR back to a point where it does (roughly) the minimum required to use the config file.


<a id="org6baf40c"></a>

## TODO add code for reading categorising keys from config

-   [X] add/use config for `flux_timeseries`
-   [X] remove old commented out required keys
-   [X] write PR message summarising current state of metadata processing
-   [ ] write issue with next steps


<a id="orgc3f0c3d"></a>

## TODO remaining metadata tasks

-   [ ] update `Flux.transform_data`


<a id="orgac1a7d7"></a>

## TODO fix how optional/informative metadata is processed

-   currently `optional_metadata` does both jobs, we want to split this out
-   tests need to change: e.g. `test_standardise_footprints_different_datasources`


<a id="orga03e37d"></a>

## TODO summarise existing state

-   categorising metadata is determined solely by the (&ldquo;metakeys&rdquo; in the) config file
-   all of `optional_metadata` is combined with the metadata output by the parser (`optional_metadata` overwrites what comes out of the parser)
-   any &ldquo;optional metakeys&rdquo; found in `optional_metadata` will be used for datasource lookup (so remainder of `optional_metadata` is &ldquo;informational&rdquo;)
-   an error is raised by `BaseStore.get_lookup_keys` if any key in `optional_metadata` is a required metakey (as defined by the config)
-   For flux and flux timeseries, the keyword arguments from `standardise_...` that are optional *for the parser* will overwrite items with the same keys in `optional_metadata`

In summary: informational metadata and &ldquo;optional&rdquo; categorising metadata can both be passed through the `optional_metadata` argument, but `optional_metadata` cannot conflict with the &ldquo;required metakeys&rdquo; defined in the config. Categorising metadata is determined (solely) by the metakeys config file.


<a id="orgf50c35c"></a>

# TODO make methods (and CLI?) for modifying config file


<a id="org3c5cc25"></a>

# TODO extract repeated code for metadata handling from subclasses of `BaseStore`

This code needs to be modified in each subclass in order for the handling of metadata to be changed.
&#x2013;> use &ldquo;group related code&rdquo; type refactor


<a id="org6a7e2e3"></a>

# TODO add option for passing additional categorising keys via kwargs

Two options:

1.  anything passed by kwargs is used for categorising
    -   easy for user to add more keys
    -   issues:
        -   user might misspell key, no way to check
        -   need to track origin of metadata (i.e. kwargs) in order to know if it should be used for categorising
2.  anything passed by kwargs must be specified in the config
    -   this adds a barrier for the user
    -   need to have a convenient way to add extra keys
    -   simplifies logic because we can rely on the config to know what info is needed for categorising


<a id="org99b94e0"></a>

# TODO parser organisation

-   function to get list of required parameters (alternatively, use kwargs, raise value errors?)
-   function to display what parameters are needed for a given source format
-   attribute parsing? (could happen afterwards)


<a id="org581a31e"></a>

# TODO Centralise metadata processing


<a id="org306ebaa"></a>

# Random related ideas

-   one metastore, with &ldquo;data type&rdquo; as a key (would probably need to use mongo db to avoid concurrency issues
-   `ObsData` etc. object should have methods for processing
    -   then e.g. `get_obs_surface` could be something like: `SearchResults.retrieve().rename_to_mf().resample(averaging_period)`
-   Increased search flexibility:
    -   using lists for &ldquo;or&rdquo; (already done in `search`)
    -   using dicts for &ldquo;and&rdquo; (already done in `search`?)
-   How should data that covers a period be stored?
    -   Also, can we use pandas&rsquo; functionality to replace some of our code?
    -   Is there CF (or other) guidance on this?

**Comment by brendan-m-murphy** [comment]
Note: PR #1064 adds the ability to search by "negative lookup", which is something we discussed adding in relation to the metadata updates.

**Comment by rt17603** [comment]
Will also be added to the summary above but we should also consider "internal" flags set by openghg which are never set by the user but are used for data lookup. Can store these within the code (function etc.) rather than within the config but should also be used when constructing the metadata and distinguishing keys.

**Comment by rt17603** [comment]
Tasks on this PR completed - new umbrella issue opened up to continue tracking metadata  updates #1092
