### ISSUE TITLE
Read and interpret InTEM format (emissions data)

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#797]
### Is your feature request related to a problem?

We need to be able to understand and read InTEM output data into OpenGHG. This will be both:

 - 1D emissions totals (and uncertainties)
 - 2D + time emissions maps (no uncertainties)

We should confirm with Alistair Manning about the latest output format for this.

### Additional context

This will include 1D emissions data and so Issue #301 will need to be completed for this.

**Comment by SutarPrasad** [comment]
Task Breakdown:

**1D emissions totals (and uncertainties)**

- [ ] Fetch (*.txt) files and convert them to (*.nc).
- [ ] Get the format confirmed.
- [ ] Populate the object store with the new .nc files.
       - [ ]  Might need to modify obsData, ObsSurface and plot_timeseries.

**Comment by SutarPrasad** [comment]
- [ ] parse function to read from "netcdf" files provided by Allistair - Final structure not confirmed

**Comment by gareth-j** [comment]
## TODO

1. Create a `parse_intem` function in `openghg.standardise.emissions`, this needs to
- [ ] read the NetCDF
- [ ] read metadata from the filename? Will it just be the whole DECC network for each file?
- [ ] create a metadata dictionary from the attributes (there aren't many), adding species, sites, network, domain, source = "intem"
- [ ] check the dataset using `Emissions.validate_data`
- [ ] create a dictionary `{"data": parsed_dataset, "metadata": metadata_dict}
- [ ] return this dict

2. Add an `INTEM` type to `EmissionsTypes(Enum)` in `openghg.types._enum.py`
3. Make sure `Emissions.read_file` can use the parser to read the file
4. Add some tests for the new data type, create a small (<= 50 kB if possible) NetCDF using `ds.head(integer_that_makes_sense)`
5. Add adding INTEM files to the documentation
6. Add to changelog
